version: '3'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '4306:3306'
    volumes:
      - ./docker/database/data:/var/lib/mysql
      - ./docker/database/init.sql:/tmp/init.sql
  php-fpm:
    build:
      dockerfile: ./docker/php-fpm/Dockerfile
      context: .
    depends_on:
      - database
    #restart: on-failure:10
    command: bash -c "composer install &&
             php artisan key:generate &&
             php artisan migrate:fresh --seed &&
             chown -R www-data:www-data /var/www &&
             chmod -R 755 /var/www/storage &&
             php-fpm"
    volumes:
      - .:/var/www
    ports:
    - '9000:9000'
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
      - "443:443"


